name: "Test AWS OIDC Access"

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # Required for OIDC authentication
  contents: read

jobs:
  escalate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1  # Change if your AWS region is different
          role-to-assume: ${{ secrets.READ_ROLE }}
          role-session-name: OIDCSession

      - name: Verify AWS Access
        run: aws sts get-caller-identity

      - name: Retrieve Secret (Flag)
        run: aws secretsmanager get-secret-value --secret-id lab-flag
